name: Client

on:
    push:
        branches:
            - dev
jobs:
    build:
        name: Build and Deploy
        runs-on: ubuntu-latest
        steps:
           - name: Executing remote SSH commands using key
             uses: appleboy/ssh-action@v1.0.3
             with:
                host: ${{ secrets.HOST }}
                username: ${{ secrets.USERNAME }}
                key: ${{ secrets.KEY }}
                port: ${{ secrets.PORT }}
                script: |
                      cd /home/ubuntu/
                      echo "🔄 Cтягиваем код с github"
                      echo "🗑 Очищаем следы прошлых запусков, если имеются"
                      if [ -d "streaming-client" ]; then
                          rm -rf streaming-client
                      fi
                      git clone git@github.com:VladyslavDobrovolskyi/streaming-client.git
                      cd streaming-client
                      git checkout dev
                      git pull
                      rm -rf .git

                      echo "🔄 Остановка и пересборка контейнера"
                      echo "🛑 Проверка наличия контейнера streaming-client"
                      if [ $(docker ps -q -f name=streaming-client) ]; then
                          echo "🛑 Остановка контейнера streaming-client"
                          docker stop streaming-client || true
                          docker rm streaming-client || true
                      fi

                      echo "🗑 Удаление предыдущего образа streaming-client, если он существует"
                      if [ $(docker images -q streaming-client) ]; then
                          docker rmi streaming-client || true
                      fi

                      echo "🛠 Пересборка контейнера streaming-client без кэша"
                      docker build -t streaming-client .

                      echo "🔍 Проверка наличия сети streaming-network"
                      if [ ! $(docker network ls -q -f name=streaming-network) ]; then
                          echo "🌐 Сеть streaming-network не найдена, создаем сеть"
                          docker network create streaming-network
                      fi


                      echo "🚀 Запуск контейнера streaming-client"
                      docker run -d --name streaming-client \
                        --network streaming-network \
                        --restart always \
                        -p 7777:7777 \
                        streaming-client

                      echo "🔍 Проверка, что контейнер streaming-client поднялся"
                      if [ $(docker ps -q -f name=streaming-client) ]; then
                          echo "✅ Контейнер streaming-client успешно запущен"
                      else
                          echo "❌ Контейнер streaming-client не запущен"
                          exit 1
                      fi


                       cd /home/ubuntu/

                      echo "🔍 Проверка наличия контейнеров postgres и nginx"
                      if [ ! $(docker ps -q -f name=postgres) ]; then
                          echo "❌ Контейнер postgres не найден, запускаем docker-compose up"
                          docker-compose up -d postgres
                      fi
                      if [ ! $(docker ps -q -f name=nginx) ]; then
                          echo "❌ Контейнер nginx не найден, запускаем docker-compose up"
                          docker-compose up -d nginx
                      fi

                      echo "🗑 Очищаем пространство"
                      if [ -d "streaming-client" ]; then
                          rm -rf streaming-client
                      fi

                      echo "✅ Деплой завершен успешно!"
