name: Remote SSH Command and CI Workflow

on:
    push:
        branches:
            - dev
jobs:
    build:
        name: Build and Deploy
        runs-on: ubuntu-latest
        steps:
            - name: Executing remote SSH commands using password
              uses: appleboy/ssh-action@v1.0.3
              with:
                  host: ${{ secrets.HOST }}
                  username: ${{ secrets.USERNAME }}
                  password: ${{ secrets.PASSWORD }}
                  port: ${{ secrets.PORT }}
                  script: |
                      cd /home/ubuntu/
                      echo "🔄 Скачиваем код с GitHub"
                      if [ -d "streaming-client" ]; then
                          echo "🗑 Удаляем старую папку streaming-client"
                          rm -rf streaming-client
                      fi
                      git clone git@github.com:VladyslavDobrovolskyi/streaming-client.git
                      cd streaming-client
                      git checkout dev
                      git pull
                      rm -rf .git

                      echo "🔄 Проверяем и управляем контейнером streaming-client"
                      if [ $(docker ps -q -f name=streaming-client) ]; then
                          echo "🛑 Останавливаем контейнер streaming-client"
                          docker stop streaming-client || true
                          docker rm streaming-client || true
                      fi

                      echo "🛠 Пересобираем контейнер streaming-client"
                      docker-compose build streaming-client --no-cache

                      echo "🚀 Запускаем контейнер streaming-client"
                      docker-compose up -d streaming-client

                      echo "🔍 Проверяем статус контейнера streaming-client"
                      if [ $(docker ps -q -f name=streaming-client) ]; then
                          echo "✅ Контейнер streaming-client успешно запущен"
                      else
                          echo "❌ Не удалось запустить контейнер streaming-client"
                          exit 1
                      fi

                      echo "🗑 Удаляем локальную копию streaming-client"
                      cd ..
                      rm -rf streaming-client

                      echo "✅ Деплой завершён!"
